spring:
  application:
     name: accounts-service
     
  datasource:
    url: jdbc:mysql://localhost/micro
    username: root
    password: root
  jpa:
    generate-ddl: true

    
server:
  port: 0 
  
logging:
  level: 
    httpclient.wire: DEBUG 
    
    
  
 
 
  